### ISSUE TITLE
Error from sklearn.externals import joblib ImportError: cannot import name 'joblib' from 'sklearn.externals' (/usr/local/lib/python3.7/site-packages/sklearn/externals/__init__.py)

### ISSUE THREAD

**Issue by boypanjaitan16** [Hironsan/HateSonar#86]
I got this error, I think it's something about joblib library

File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/hatesonar/__init__.py", line 1, in <module>
    from hatesonar.api import Sonar
  File "/usr/local/lib/python3.7/site-packages/hatesonar/api.py", line 12, in <module>
    from sklearn.externals import joblib
ImportError: cannot import name 'joblib' from 'sklearn.externals' (/usr/local/lib/python3.7/site-packages/sklearn/externals/__init__.py)

**Comment by AlphaYui** [comment]
The same issue occurs for me with Python 3.6. It seems to be caused by a recent update to scikit-learn:
https://stackoverflow.com/questions/56113916/cannot-import-sklearn-from-sklearn-externals-joblib

I was able to resolve it by uninstalling the scikit-learn package and specifically reinstalling version 0.20.3.

**Comment by hackerlikecomputer** [comment]
Same issue here

**Comment by acastrob** [comment]
Thank you, AlphaYui.

You are right. Uninstalling the current version (pip uninstall scikit-learn) it and installing version 0.30.3 did it for me:

sudo pip install --ignore-installed scikit-learn==0.20.3

**Comment by Hironsan** [comment]
I replaced `sklearn.externals.joblib` with `joblib` and updated hatesonar.
- https://pypi.org/project/hatesonar/0.0.7/
